POST http://localhost:4321/auth/sign-in
Accept: application/json

{
"email": "test@gmail.com",
"password":"qwerty123"
}

###

POST http://localhost:4321/auth/sign-up
Accept: application/json

{
"email": "test@gmail.com",
"password":"qwerty123"
}

###

POST http://localhost:4321/seller
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzgzMDYzMTAsImlhdCI6MTY3ODI5OTExMCwiVXNlcklEIjoxfQ.xJ3iQq2GaWDYYKwuYFEl25bZ25cAlcD5FVDUDU8kFJU

{
"name":"Max",
"phoneNumber":"+380683062975"
}

###

POST http://localhost:4321/product
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzgzMTEwNDQsImlhdCI6MTY3ODMwMzg0NCwiVXNlcklEIjoxfQ.SZMhG-OSSBHqHir2gNFHvQIgJyeszXLZYscA8q3LhTw

{
"title": "Laptop",
"sellerId": 1,
"price":14.25
}

