POST http://localhost:8080/auth/sign-in
Accept: application/json

{
"phoneNumber": "+380683062975",
"password": "qwerty123",
"name":"Max"
}

###

POST http://localhost:8080/auth/sign-up
Accept: application/json

{
"phoneNumber": "+380683062975",
"password": "qwerty123",
"name":"Max"
}

