version: '3.9'
services:
  app:
    build: ./
    command: ./main
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

  db:
    platform: linux/amd64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'adtelligent-db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '30042003'
      MYSQL_ROOT_PASSWORD: '30042003'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db: