version: '3.9'
services:
  app:
    build: ./
    command: ./main
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql/mysql-server:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'adtelligent-db'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'qwerty123'
      MYSQL_ROOT_PASSWORD: 'qwerty123'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
